// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cqCarlxzpf8ccmJR0OaIPaGS4YWrza4',
    appId: '1:277318646487:web:04c261942e280052bb4e92',
    messagingSenderId: '277318646487',
    projectId: 'whatsapp-backend-16a9f',
    authDomain: 'whatsapp-backend-16a9f.firebaseapp.com',
    storageBucket: 'whatsapp-backend-16a9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6eh5OhsHwq4347G06Fil-FQQRHa54iw',
    appId: '1:277318646487:android:c9ffd958ab665685bb4e92',
    messagingSenderId: '277318646487',
    projectId: 'whatsapp-backend-16a9f',
    storageBucket: 'whatsapp-backend-16a9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVLIF0MdNjjWDenrY_TlJHr_Vb2ORghKY',
    appId: '1:277318646487:ios:dee49ef79ffd696fbb4e92',
    messagingSenderId: '277318646487',
    projectId: 'whatsapp-backend-16a9f',
    storageBucket: 'whatsapp-backend-16a9f.appspot.com',
    iosClientId: '277318646487-pn68ap4h7n4n3rl9rbg0ulhu3lu2lvcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVLIF0MdNjjWDenrY_TlJHr_Vb2ORghKY',
    appId: '1:277318646487:ios:dee49ef79ffd696fbb4e92',
    messagingSenderId: '277318646487',
    projectId: 'whatsapp-backend-16a9f',
    storageBucket: 'whatsapp-backend-16a9f.appspot.com',
    iosClientId: '277318646487-pn68ap4h7n4n3rl9rbg0ulhu3lu2lvcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsap',
  );
}
